// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/tr181_api.proto

package tr181pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricType    string                 `protobuf:"bytes,1,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`       // например cpu-usage
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"` // серийный номер устройства
	From          int64                  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`                                    // Unix timestamp начала периода
	To            int64                  `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`                                        // Unix timestamp конца периода
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRequest) Reset() {
	*x = MetricRequest{}
	mi := &file_api_proto_tr181_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRequest) ProtoMessage() {}

func (x *MetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tr181_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRequest.ProtoReflect.Descriptor instead.
func (*MetricRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tr181_api_proto_rawDescGZIP(), []int{0}
}

func (x *MetricRequest) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *MetricRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *MetricRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *MetricRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type MetricValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Time          int64                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricValue) Reset() {
	*x = MetricValue{}
	mi := &file_api_proto_tr181_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricValue) ProtoMessage() {}

func (x *MetricValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tr181_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricValue.ProtoReflect.Descriptor instead.
func (*MetricValue) Descriptor() ([]byte, []int) {
	return file_api_proto_tr181_api_proto_rawDescGZIP(), []int{1}
}

func (x *MetricValue) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricValue) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type MetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*MetricValue         `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricResponse) Reset() {
	*x = MetricResponse{}
	mi := &file_api_proto_tr181_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricResponse) ProtoMessage() {}

func (x *MetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tr181_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricResponse.ProtoReflect.Descriptor instead.
func (*MetricResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tr181_api_proto_rawDescGZIP(), []int{2}
}

func (x *MetricResponse) GetMetrics() []*MetricValue {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type AlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertType     string                 `protobuf:"bytes,1,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"` // например high-cpu-usage
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	From          int64                  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRequest) Reset() {
	*x = AlertRequest{}
	mi := &file_api_proto_tr181_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRequest) ProtoMessage() {}

func (x *AlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tr181_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRequest.ProtoReflect.Descriptor instead.
func (*AlertRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tr181_api_proto_rawDescGZIP(), []int{3}
}

func (x *AlertRequest) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

func (x *AlertRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *AlertRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *AlertRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

type AlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"` // среднее значение за период
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // количество алертов
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertResponse) Reset() {
	*x = AlertResponse{}
	mi := &file_api_proto_tr181_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertResponse) ProtoMessage() {}

func (x *AlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tr181_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertResponse.ProtoReflect.Descriptor instead.
func (*AlertResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tr181_api_proto_rawDescGZIP(), []int{4}
}

func (x *AlertResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AlertResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_proto_tr181_api_proto protoreflect.FileDescriptor

const file_api_proto_tr181_api_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/tr181_api.proto\x12\ttr181.api\"y\n" +
	"\rMetricRequest\x12\x1f\n" +
	"\vmetric_type\x18\x01 \x01(\tR\n" +
	"metricType\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\x03R\x02to\"7\n" +
	"\vMetricValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x03R\x04time\"B\n" +
	"\x0eMetricResponse\x120\n" +
	"\ametrics\x18\x01 \x03(\v2\x16.tr181.api.MetricValueR\ametrics\"v\n" +
	"\fAlertRequest\x12\x1d\n" +
	"\n" +
	"alert_type\x18\x01 \x01(\tR\talertType\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\x03R\x02to\";\n" +
	"\rAlertResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\x8b\x01\n" +
	"\bTR181Api\x12@\n" +
	"\tGetMetric\x12\x18.tr181.api.MetricRequest\x1a\x19.tr181.api.MetricResponse\x12=\n" +
	"\bGetAlert\x12\x17.tr181.api.AlertRequest\x1a\x18.tr181.api.AlertResponseB\x1dZ\x1bgolang-test-dev/api/tr181pbb\x06proto3"

var (
	file_api_proto_tr181_api_proto_rawDescOnce sync.Once
	file_api_proto_tr181_api_proto_rawDescData []byte
)

func file_api_proto_tr181_api_proto_rawDescGZIP() []byte {
	file_api_proto_tr181_api_proto_rawDescOnce.Do(func() {
		file_api_proto_tr181_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_tr181_api_proto_rawDesc), len(file_api_proto_tr181_api_proto_rawDesc)))
	})
	return file_api_proto_tr181_api_proto_rawDescData
}

var file_api_proto_tr181_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_tr181_api_proto_goTypes = []any{
	(*MetricRequest)(nil),  // 0: tr181.api.MetricRequest
	(*MetricValue)(nil),    // 1: tr181.api.MetricValue
	(*MetricResponse)(nil), // 2: tr181.api.MetricResponse
	(*AlertRequest)(nil),   // 3: tr181.api.AlertRequest
	(*AlertResponse)(nil),  // 4: tr181.api.AlertResponse
}
var file_api_proto_tr181_api_proto_depIdxs = []int32{
	1, // 0: tr181.api.MetricResponse.metrics:type_name -> tr181.api.MetricValue
	0, // 1: tr181.api.TR181Api.GetMetric:input_type -> tr181.api.MetricRequest
	3, // 2: tr181.api.TR181Api.GetAlert:input_type -> tr181.api.AlertRequest
	2, // 3: tr181.api.TR181Api.GetMetric:output_type -> tr181.api.MetricResponse
	4, // 4: tr181.api.TR181Api.GetAlert:output_type -> tr181.api.AlertResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_tr181_api_proto_init() }
func file_api_proto_tr181_api_proto_init() {
	if File_api_proto_tr181_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_tr181_api_proto_rawDesc), len(file_api_proto_tr181_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_tr181_api_proto_goTypes,
		DependencyIndexes: file_api_proto_tr181_api_proto_depIdxs,
		MessageInfos:      file_api_proto_tr181_api_proto_msgTypes,
	}.Build()
	File_api_proto_tr181_api_proto = out.File
	file_api_proto_tr181_api_proto_goTypes = nil
	file_api_proto_tr181_api_proto_depIdxs = nil
}
