// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/proto/tr181_api.proto

package tr181pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TR181Api_GetMetric_FullMethodName = "/tr181.api.TR181Api/GetMetric"
	TR181Api_GetAlert_FullMethodName  = "/tr181.api.TR181Api/GetAlert"
)

// TR181ApiClient is the client API for TR181Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TR181 API Service - gRPC endpoints для метрик и алертов
type TR181ApiClient interface {
	// GetMetric - получение метрик за период
	GetMetric(ctx context.Context, in *MetricRequest, opts ...grpc.CallOption) (*MetricResponse, error)
	// GetAlert - получение статистики алертов за период
	GetAlert(ctx context.Context, in *AlertRequest, opts ...grpc.CallOption) (*AlertResponse, error)
}

type tR181ApiClient struct {
	cc grpc.ClientConnInterface
}

func NewTR181ApiClient(cc grpc.ClientConnInterface) TR181ApiClient {
	return &tR181ApiClient{cc}
}

func (c *tR181ApiClient) GetMetric(ctx context.Context, in *MetricRequest, opts ...grpc.CallOption) (*MetricResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricResponse)
	err := c.cc.Invoke(ctx, TR181Api_GetMetric_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tR181ApiClient) GetAlert(ctx context.Context, in *AlertRequest, opts ...grpc.CallOption) (*AlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertResponse)
	err := c.cc.Invoke(ctx, TR181Api_GetAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TR181ApiServer is the server API for TR181Api service.
// All implementations must embed UnimplementedTR181ApiServer
// for forward compatibility.
//
// TR181 API Service - gRPC endpoints для метрик и алертов
type TR181ApiServer interface {
	// GetMetric - получение метрик за период
	GetMetric(context.Context, *MetricRequest) (*MetricResponse, error)
	// GetAlert - получение статистики алертов за период
	GetAlert(context.Context, *AlertRequest) (*AlertResponse, error)
	mustEmbedUnimplementedTR181ApiServer()
}

// UnimplementedTR181ApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTR181ApiServer struct{}

func (UnimplementedTR181ApiServer) GetMetric(context.Context, *MetricRequest) (*MetricResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetric not implemented")
}
func (UnimplementedTR181ApiServer) GetAlert(context.Context, *AlertRequest) (*AlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlert not implemented")
}
func (UnimplementedTR181ApiServer) mustEmbedUnimplementedTR181ApiServer() {}
func (UnimplementedTR181ApiServer) testEmbeddedByValue()                  {}

// UnsafeTR181ApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TR181ApiServer will
// result in compilation errors.
type UnsafeTR181ApiServer interface {
	mustEmbedUnimplementedTR181ApiServer()
}

func RegisterTR181ApiServer(s grpc.ServiceRegistrar, srv TR181ApiServer) {
	// If the following call panics, it indicates UnimplementedTR181ApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TR181Api_ServiceDesc, srv)
}

func _TR181Api_GetMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TR181ApiServer).GetMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TR181Api_GetMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TR181ApiServer).GetMetric(ctx, req.(*MetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TR181Api_GetAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TR181ApiServer).GetAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TR181Api_GetAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TR181ApiServer).GetAlert(ctx, req.(*AlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TR181Api_ServiceDesc is the grpc.ServiceDesc for TR181Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TR181Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tr181.api.TR181Api",
	HandlerType: (*TR181ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetric",
			Handler:    _TR181Api_GetMetric_Handler,
		},
		{
			MethodName: "GetAlert",
			Handler:    _TR181Api_GetAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/tr181_api.proto",
}
